<?php 
use Illuminate\Support\Facades\Schema;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
//Generated By PlantUML Command
class Create4votes extends Migration{
	public function up(){ 
 		Schema::create('votes', function (Blueprint $table) { 
			$table->bigIncrements('id');
			$table->bigInteger('elector_id')->unsigned();
			$table->foreign('elector_id')->references('id')->on('electors');
			$table->bigInteger('candidate_id')->unsigned();
			$table->foreign('candidate_id')->references('id')->on('candidates');
			$table->date('date');
			$table->string('hour');
			$table->timestamps();
		});
 	} 
	public function down(){
 
	} 
}