<?php 
use Illuminate\Support\Facades\Schema;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
//Generated By PlantUML Command
class Create2electors extends Migration{
	public function up(){ 
 		Schema::create('electors', function (Blueprint $table) { 
			$table->bigIncrements('id');
			$table->bigInteger('people_dni')->unsigned();
			$table->foreign('people_dni')->references('dni')->on('peoples');
			$table->timestamps();
		});
 	} 
	public function down(){
 
	} 
}