<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class Candidate extends Model{

    public function People(){
        return $this->belongsTo('App\Models\People','people_dni');
    }

    public function Vote(){
        return $this->hasMany('App\Models\4Vote');
    }

}