<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class People extends Model{

    public function Elector(){
        return $this->hasMany('App\Models\Elector','people_dni','dni');
    }

    public function Candidate(){
        return $this->hasMany('App\Models\Candidate','people_dni','dni');
    }

}