<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class Vote extends Model{

    public function Elector(){
        return $this->belongsTo('App\Models\Elector');
    }

    public function Candidate(){
        return $this->belongsTo('App\Models\Candidate');
    }

}